CREATE TABLE IF NOT EXISTS `click-stream-463520.clickstream_analytics.dead_letter_table` (
  timestamp STRING,
  user_id STRING,
  session_id STRING,
  url STRING,
  http_status_code STRING,
  response_time_ms STRING,
  event_type STRING,
  product_id STRING,
  price STRING,
  colour STRING,
  category STRING,
  geolocation STRING,
  user_agent STRING,
  entry_url STRING,
  exit_url STRING,
  session_start_time STRING,
  session_end_time STRING,
  click_timestamp STRING,
  error_type STRING,
  error_message STRING,
  first_visit_timestamp STRING,
  session_count STRING,
  error_message_time TIMESTAMP,
  error_stack_trace STRING
)
